import ApolloClient from "apollo-boost";
import { URL_HASURA_API } from "@/apollo/hasura-client/url-api";

export const clientHasura = "clientHasura";

const apolloClientHasura = new ApolloClient({
  uri: URL_HASURA_API,
  headers: {
    "content-type": "application/json",
    authorization:
      "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik9FWTJSVGM1UlVOR05qSXhSRUV5TURJNFFUWXdNekZETWtReU1EQXdSVUV4UVVRM05EazFNQSJ9.eyJodHRwczovL2hhc3VyYS5pby9qd3QvY2xhaW1zIjp7IngtaGFzdXJhLWRlZmF1bHQtcm9sZSI6InVzZXIiLCJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjpbInVzZXIiXSwieC1oYXN1cmEtdXNlci1pZCI6ImF1dGgwfDYzNzBiNGRiYmVjNTFiZGZkNzZkNjdiOCJ9LCJuaWNrbmFtZSI6InNlcmdpby5zYWxjZWRvLmRldisxIiwibmFtZSI6InNlcmdpby5zYWxjZWRvLmRldisxQGdtYWlsLmNvbSIsInBpY3R1cmUiOiJodHRwczovL3MuZ3JhdmF0YXIuY29tL2F2YXRhci9hOWQ2NTE2MjAyNDUyMzAyODgwZDBhYzE0MWFiM2YyMT9zPTQ4MCZyPXBnJmQ9aHR0cHMlM0ElMkYlMkZjZG4uYXV0aDAuY29tJTJGYXZhdGFycyUyRnNlLnBuZyIsInVwZGF0ZWRfYXQiOiIyMDIyLTExLTI4VDIwOjM4OjA3LjE3MFoiLCJpc3MiOiJodHRwczovL2dyYXBocWwtdHV0b3JpYWxzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2MzcwYjRkYmJlYzUxYmRmZDc2ZDY3YjgiLCJhdWQiOiJQMzhxbkZvMWxGQVFKcnprdW4tLXdFenFsalZOR2NXVyIsImlhdCI6MTY2OTkxOTMxNywiZXhwIjoxNjY5OTU1MzE3LCJhdF9oYXNoIjoidzBtMFBIMnRrZWJBNzNpRUlyVWp6ZyIsInNpZCI6ImdUV3pHVDRjeU0xYUtDYTBKX1JlYTk2N1ltSUdFYVlFIiwibm9uY2UiOiJzS0JlYm5WUXBsRXlDUWJ3MG53cnROMWdubkY1bWU5SSJ9.HxjrAcWssrmtOjaAUX3WbJwusmiA5gOr3hNm7MwSICjRflbw_OzGrcbbLhtMUV8ftjzYzE_AJPAB6Huptr2b5N1kR99rC3CUZVaQk4Q7byNRLxL47MVys47WvzOfPAHgOhTvbw80Uqs38HFCyNdz81KqN5eoo_58qGALK_VTcQZg1yT_qoUKYu5Wwl6Ra7kLjLmkYc2gWT_ZNjwFSLh7VCHPcmweAggf8-HRRkOpvk4Ga0xjudwEGVimrhGM18KPDAR61zKZDJLPhs29tZV7pQR0NzelreMqkzZbsKbmkgq43lt-cHQkGT8SMtaLyKBVjyNgeZperb-4wQZ9qiwnsg",
  },
});

export default apolloClientHasura;
